const ADD_OTHER_EVENT = "ADD_OTHER_EVENT";
const DELETE_OTHER_EVENT = "DELETE_OTHER_EVENT";
const UPDATE_OTHER_EVENT = "UPDATE_OTHER_EVENT";
const ADD_PERSONAL_EVENT = "ADD_PERSONAL_EVENT";
const DELETE_PERSONAL_EVENT = "DELETE_PERSONAL_EVENT";
const UPDATE_PERSONAL_EVENT = "UPDATE_PERSONAL_EVENT";
const ADD_PROFESSIONAL_EVENT = "ADD_PROFESSIONAL_EVENT";
const DELETE_PROFESSIONAL_EVENT = "DELETE_PROFESSIONAL_EVENT";
const UPDATE_PROFESSIONAL_EVENT = "UPDATE_PROFESSIONAL_EVENT";
const ADD_SOCIAL_EVENT = "ADD_SOCIAL_EVENT";
const DELETE_SOCIAL_EVENT = "DELETE_SOCIAL_EVENT";
const UPDATE_SOCIAL_EVENT = "UPDATE_SOCIAL_EVENT";
export {
  ADD_OTHER_EVENT,
  DELETE_OTHER_EVENT,
  UPDATE_OTHER_EVENT,
  ADD_PERSONAL_EVENT,
  DELETE_PERSONAL_EVENT,
  UPDATE_PERSONAL_EVENT,
  ADD_PROFESSIONAL_EVENT,
  DELETE_PROFESSIONAL_EVENT,
  UPDATE_PROFESSIONAL_EVENT,
  ADD_SOCIAL_EVENT,
  DELETE_SOCIAL_EVENT,
  UPDATE_SOCIAL_EVENT,
};
